# Generated by Django 5.2.8 on 2025-12-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComment',
            new_name='Comment',
        ),
    ]
