# Generated by Django 5.2.8 on 2025-12-03 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_usercomment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kommentar', 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['lastname'], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aufgabe', 'verbose_name_plural': 'Aufgaben'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tester_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='Unbekannt', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='api.employee', verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='api.employee', verbose_name='Zugewiesener Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('urgent', 'Dringend')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_tasks', to='api.employee', verbose_name='Tester'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tasks', to='api.employee', verbose_name='Aktualisiert von'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', '-created_at'], name='api_comment_task_id_7d4615_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['role', 'is_active'], name='api_employe_role_968344_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='api_employe_departm_a88d93_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='api_task_status_c958b5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['employee', 'status'], name='api_task_employe_cc8b42_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['start_date', 'end_date'], name='api_task_start_d_741224_idx'),
        ),
    ]
