# Generated by Django 5.2.8 on 2025-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_created_by_alter_task_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nicht_zugewiesen', 'Nicht zugewiesen'), ('offen', 'Offen'), ('abgeschlossen', 'Abgeschlossen'), ('archiviert', 'Archiviert')], db_index=True, default='nicht_zugewiesen', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='api_task_created_0e57a6_idx'),
        ),
    ]
