import Keycloak from 'keycloak-js';

export const dummyKeycloak = {
  init: () => Promise.resolve(false),
  login: () => Promise.resolve(),
  logout: () => Promise.resolve(),
  register: () => Promise.resolve(),
  accountManagement: () => Promise.resolve(),
  createLoginUrl: () => '',
  createLogoutUrl: () => '',
  createRegisterUrl: () => '',
  createAccountUrl: () => '',
  isTokenExpired: () => true,
  updateToken: () => Promise.resolve(false),
  clearToken: () => {},
  hasRealmRole: () => false,
  hasResourceRole: () => false,
  loadUserProfile: () => Promise.resolve({} as any),
  loadUserInfo: () => Promise.resolve({} as any),
  
  token: undefined,
  tokenParsed: undefined,
  refreshToken: undefined,
  refreshTokenParsed: undefined,
  idToken:undefined,
  idTokenParsed: undefined,
  realmAccess: undefined,
  resourceAccess: undefined,
  authenticated: false,
  subject: undefined,
  timeSkew: 0,
  responseMode: undefined,
  flow: 'standard',
  adapter: 'default',
  responseType: undefined,
  
  onReady: undefined,
  onAuthSuccess: undefined,
  onAuthError: undefined,
  onAuthRefreshSuccess: undefined,
  onAuthRefreshError: undefined,
  onAuthLogout: undefined,
  onTokenExpired: undefined,
} as unknown as Keycloak;